
import { UserInfo, AnalysisResult } from '../types';

import jsPDF from 'jspdf';

export const generatePdf = (userInfo: UserInfo, result: AnalysisResult) => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text("Diabetic Retinopathy Analysis Report", 105, 20, { align: 'center' });

    // Patient Information
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text("Patient Information", 20, 40);
    doc.setLineWidth(0.5);
    doc.line(20, 42, 190, 42);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Name: ${userInfo.name}`, 20, 50);
    doc.text(`Age: ${userInfo.age}`, 20, 58);
    doc.text(`Email: ${userInfo.email}`, 20, 66);

    // Analysis Results
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text("Analysis Results", 20, 86);
    doc.line(20, 88, 190, 88);

    doc.setFontSize(12);
    doc.text(`Diagnosis: ${result.diagnosis}`, 20, 96);
    doc.text(`Confidence: ${result.confidence.toFixed(2)}%`, 20, 104);
    doc.text(`Risk Level: ${result.riskLevel}`, 20, 112);

    // Recommendations
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text("Recommendations", 20, 132);
    doc.line(20, 134, 190, 134);

    doc.setFontSize(12);
    const splitRecommendations = doc.splitTextToSize(result.recommendations, 170);
    doc.text(splitRecommendations, 20, 142);

    // Disclaimer
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    const disclaimer = "Disclaimer: This report is generated by an AI model and is for informational purposes only. It is not a substitute for a professional medical diagnosis. Please consult a qualified healthcare provider for any medical concerns.";
    const splitDisclaimer = doc.splitTextToSize(disclaimer, 170);
    const disclaimerY = 142 + (splitRecommendations.length * 5) + 20;
    doc.text(splitDisclaimer, 20, disclaimerY);
    
    doc.save(`Diabetic_Retinopathy_Report_${userInfo.name.replace(/\s/g, '_')}.pdf`);
};
